
// generated automatically by data-raw/update-libgeos-api.R - do not edit by hand!
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

// whereas libgeos.h contains declarations for function *pointers*
// these are the declarations for the functions in geos_c.h
// we cannnot include geos_c.h because the magic defines GEOS
// uses create problems for the LTO build of R-devel
typedef struct GEOSContextHandle_HS *GEOSContextHandle_t;
typedef void (*GEOSMessageHandler)(const char *fmt, ...);
typedef void (*GEOSMessageHandler_r)(const char *message, void *userdata);
typedef struct GEOSGeom_t GEOSGeometry;
typedef struct GEOSPrepGeom_t GEOSPreparedGeometry;
typedef struct GEOSCoordSeq_t GEOSCoordSequence;
typedef struct GEOSSTRtree_t GEOSSTRtree;
typedef struct GEOSBufParams_t GEOSBufferParams;
typedef GEOSGeometry* GEOSGeom;
typedef GEOSCoordSequence* GEOSCoordSeq;
typedef void (*GEOSQueryCallback)(void *item, void *userdata);
typedef int (*GEOSDistanceCallback)(const void *item1, const void* item2, double* distance, void* userdata);
typedef void (GEOSInterruptCallback)();
typedef struct GEOSWKTReader_t GEOSWKTReader;
typedef struct GEOSWKTWriter_t GEOSWKTWriter;
typedef struct GEOSWKBReader_t GEOSWKBReader;
typedef struct GEOSWKBWriter_t GEOSWKBWriter;

extern GEOSContextHandle_t (*initGEOS_r)( GEOSMessageHandler, GEOSMessageHandler);
extern void (*finishGEOS_r)(GEOSContextHandle_t);
extern GEOSContextHandle_t (*GEOS_init_r)();
extern void (*GEOS_finish_r)(GEOSContextHandle_t);
extern GEOSMessageHandler (*GEOSContext_setNoticeHandler_r)(GEOSContextHandle_t, GEOSMessageHandler);
extern GEOSMessageHandler (*GEOSContext_setErrorHandler_r)(GEOSContextHandle_t, GEOSMessageHandler);
extern GEOSMessageHandler_r (*GEOSContext_setNoticeMessageHandler_r)(GEOSContextHandle_t, GEOSMessageHandler_r, void*);
extern GEOSMessageHandler_r (*GEOSContext_setErrorMessageHandler_r)(GEOSContextHandle_t, GEOSMessageHandler_r, void*);
extern const char* (*GEOSversion)();
extern GEOSGeometry* (*GEOSGeomFromWKT_r)(GEOSContextHandle_t, const char*);
extern char* (*GEOSGeomToWKT_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOS_getWKBOutputDims_r)(GEOSContextHandle_t);
extern int (*GEOS_setWKBOutputDims_r)(GEOSContextHandle_t, int);
extern int (*GEOS_getWKBByteOrder_r)(GEOSContextHandle_t);
extern int (*GEOS_setWKBByteOrder_r)(GEOSContextHandle_t, int);
extern GEOSGeometry* (*GEOSGeomFromWKB_buf_r)(GEOSContextHandle_t, const unsigned char*, size_t);
extern unsigned char* (*GEOSGeomToWKB_buf_r)(GEOSContextHandle_t, const GEOSGeometry*, size_t*);
extern GEOSGeometry* (*GEOSGeomFromHEX_buf_r)(GEOSContextHandle_t, const unsigned char*, size_t);
extern unsigned char* (*GEOSGeomToHEX_buf_r)(GEOSContextHandle_t, const GEOSGeometry*, size_t*);
extern GEOSCoordSequence* (*GEOSCoordSeq_create_r)( GEOSContextHandle_t, unsigned int, unsigned int);
extern GEOSCoordSequence* (*GEOSCoordSeq_clone_r)( GEOSContextHandle_t, const GEOSCoordSequence*);
extern void (*GEOSCoordSeq_destroy_r)(GEOSContextHandle_t, GEOSCoordSequence*);
extern int (*GEOSCoordSeq_setX_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, double);
extern int (*GEOSCoordSeq_setY_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, double);
extern int (*GEOSCoordSeq_setZ_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, double);
extern int (*GEOSCoordSeq_setXY_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, double, double);
extern int (*GEOSCoordSeq_setXYZ_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, double, double, double);
extern int (*GEOSCoordSeq_setOrdinate_r)(GEOSContextHandle_t, GEOSCoordSequence*, unsigned int, unsigned int, double);
extern int (*GEOSCoordSeq_getX_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, double*);
extern int (*GEOSCoordSeq_getY_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, double*);
extern int (*GEOSCoordSeq_getZ_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, double*);
extern int (*GEOSCoordSeq_getXY_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, double*, double*);
extern int (*GEOSCoordSeq_getXYZ_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, double*, double*, double*);
extern int (*GEOSCoordSeq_getOrdinate_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, unsigned int, double*);
extern int (*GEOSCoordSeq_getSize_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int*);
extern int (*GEOSCoordSeq_getDimensions_r)(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int*);
extern int (*GEOSCoordSeq_isCCW_r)(GEOSContextHandle_t, const GEOSCoordSequence*, char*);
extern double (*GEOSProject_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSInterpolate_r)(GEOSContextHandle_t, const GEOSGeometry*, double);
extern double (*GEOSProjectNormalized_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSInterpolateNormalized_r)( GEOSContextHandle_t, const GEOSGeometry*, double);
extern GEOSGeometry* (*GEOSBuffer_r)(GEOSContextHandle_t, const GEOSGeometry*, double, int);
extern GEOSBufferParams* (*GEOSBufferParams_create_r)( GEOSContextHandle_t);
extern void (*GEOSBufferParams_destroy_r)( GEOSContextHandle_t, GEOSBufferParams*);
extern int (*GEOSBufferParams_setEndCapStyle_r)( GEOSContextHandle_t, GEOSBufferParams*, int);
extern int (*GEOSBufferParams_setJoinStyle_r)( GEOSContextHandle_t, GEOSBufferParams*, int);
extern int (*GEOSBufferParams_setMitreLimit_r)( GEOSContextHandle_t, GEOSBufferParams*, double);
extern int (*GEOSBufferParams_setQuadrantSegments_r)( GEOSContextHandle_t, GEOSBufferParams*, int);
extern int (*GEOSBufferParams_setSingleSided_r)( GEOSContextHandle_t, GEOSBufferParams*, int);
extern GEOSGeometry* (*GEOSBufferWithParams_r)( GEOSContextHandle_t, const GEOSGeometry*, const GEOSBufferParams*, double);
extern GEOSGeometry* (*GEOSBufferWithStyle_r)(GEOSContextHandle_t, const GEOSGeometry*, double, int, int, int, double);
extern GEOSGeometry* (*GEOSSingleSidedBuffer_r)( GEOSContextHandle_t, const GEOSGeometry*, double, int, int, double, int);
extern GEOSGeometry* (*GEOSOffsetCurve_r)(GEOSContextHandle_t, const GEOSGeometry*, double, int, int, double);
extern GEOSGeometry* (*GEOSGeom_createPoint_r)( GEOSContextHandle_t, GEOSCoordSequence*);
extern GEOSGeometry* (*GEOSGeom_createPointFromXY_r)( GEOSContextHandle_t, double, double);
extern GEOSGeometry* (*GEOSGeom_createEmptyPoint_r)( GEOSContextHandle_t);
extern GEOSGeometry* (*GEOSGeom_createLinearRing_r)( GEOSContextHandle_t, GEOSCoordSequence*);
extern GEOSGeometry* (*GEOSGeom_createLineString_r)( GEOSContextHandle_t, GEOSCoordSequence*);
extern GEOSGeometry* (*GEOSGeom_createEmptyLineString_r)( GEOSContextHandle_t);
extern GEOSGeometry* (*GEOSGeom_createEmptyPolygon_r)( GEOSContextHandle_t);
extern GEOSGeometry* (*GEOSGeom_createPolygon_r)( GEOSContextHandle_t, GEOSGeometry*, GEOSGeometry**, unsigned int);
extern GEOSGeometry* (*GEOSGeom_createCollection_r)( GEOSContextHandle_t, int, GEOSGeometry**, unsigned int);
extern GEOSGeometry* (*GEOSGeom_createEmptyCollection_r)( GEOSContextHandle_t, int);
extern GEOSGeometry* (*GEOSGeom_clone_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern void (*GEOSGeom_destroy_r)(GEOSContextHandle_t, GEOSGeometry*);
extern GEOSGeometry* (*GEOSEnvelope_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSIntersection_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSConvexHull_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSMinimumRotatedRectangle_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSMinimumWidth_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSMinimumClearanceLine_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSMinimumClearance_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern GEOSGeometry* (*GEOSDifference_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSSymDifference_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSBoundary_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSUnion_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSUnaryUnion_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSCoverageUnion_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSUnionCascaded_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSPointOnSurface_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSGetCentroid_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSMinimumBoundingCircle_r)(GEOSContextHandle_t, const GEOSGeometry*, double*, GEOSGeometry**);
extern GEOSGeometry* (*GEOSNode_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSClipByRect_r)(GEOSContextHandle_t, const GEOSGeometry*, double, double, double, double);
extern GEOSGeometry* (*GEOSPolygonize_r)(GEOSContextHandle_t, const GEOSGeometry *const geoms[], unsigned int);
extern GEOSGeometry* (*GEOSPolygonize_valid_r)(GEOSContextHandle_t, const GEOSGeometry *const geoms[], unsigned int);
extern GEOSGeometry* (*GEOSPolygonizer_getCutEdges_r)( GEOSContextHandle_t, const GEOSGeometry * const geoms[], unsigned int);
extern GEOSGeometry* (*GEOSPolygonize_full_r)(GEOSContextHandle_t, const GEOSGeometry*, GEOSGeometry**, GEOSGeometry**, GEOSGeometry**);
extern GEOSGeometry* (*GEOSBuildArea_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSLineMerge_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSReverse_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSSimplify_r)(GEOSContextHandle_t, const GEOSGeometry*, double);
extern GEOSGeometry* (*GEOSTopologyPreserveSimplify_r)( GEOSContextHandle_t, const GEOSGeometry*, double);
extern GEOSGeometry* (*GEOSGeom_extractUniquePoints_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSSharedPaths_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSSnap_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double);
extern GEOSGeometry* (*GEOSDelaunayTriangulation_r)( GEOSContextHandle_t, const GEOSGeometry*, double, int);
extern GEOSGeometry* (*GEOSVoronoiDiagram_r)( GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double, int);
extern int (*GEOSSegmentIntersection_r)( GEOSContextHandle_t, double, double, double, double, double, double, double, double, double*, double*);
extern char (*GEOSDisjoint_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSTouches_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSIntersects_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSCrosses_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSWithin_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSContains_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSOverlaps_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSEquals_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSEqualsExact_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double);
extern char (*GEOSCovers_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSCoveredBy_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern const GEOSPreparedGeometry* (*GEOSPrepare_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern void (*GEOSPreparedGeom_destroy_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*);
extern char (*GEOSPreparedContains_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedContainsProperly_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedCoveredBy_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedCovers_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedCrosses_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedDisjoint_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedIntersects_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedOverlaps_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedTouches_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern char (*GEOSPreparedWithin_r)(GEOSContextHandle_t, const GEOSPreparedGeometry*, const GEOSGeometry*);
extern GEOSSTRtree* (*GEOSSTRtree_create_r)( GEOSContextHandle_t, size_t);
extern void (*GEOSSTRtree_insert_r)(GEOSContextHandle_t, GEOSSTRtree*, const GEOSGeometry*, void*);
extern void (*GEOSSTRtree_query_r)(GEOSContextHandle_t, GEOSSTRtree*, const GEOSGeometry*, GEOSQueryCallback, void*);
extern const GEOSGeometry* (*GEOSSTRtree_nearest_r)(GEOSContextHandle_t, GEOSSTRtree*, const GEOSGeometry*);
extern const void* (*GEOSSTRtree_nearest_generic_r)(GEOSContextHandle_t, GEOSSTRtree*, const void*, const GEOSGeometry*, GEOSDistanceCallback, void*);
extern void (*GEOSSTRtree_iterate_r)(GEOSContextHandle_t, GEOSSTRtree*, GEOSQueryCallback, void*);
extern char (*GEOSSTRtree_remove_r)(GEOSContextHandle_t, GEOSSTRtree*, const GEOSGeometry*, void*);
extern void (*GEOSSTRtree_destroy_r)(GEOSContextHandle_t, GEOSSTRtree*);
extern char (*GEOSisEmpty_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSisSimple_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSisRing_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSHasZ_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSisClosed_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSRelatePattern_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, const char*);
extern char* (*GEOSRelate_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern char (*GEOSRelatePatternMatch_r)(GEOSContextHandle_t, const char*, const char*);
extern char* (*GEOSRelateBoundaryNodeRule_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, int);
extern char (*GEOSisValid_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char* (*GEOSisValidReason_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char (*GEOSisValidDetail_r)(GEOSContextHandle_t, const GEOSGeometry*, int, char**, GEOSGeometry**);
extern GEOSGeometry* (*GEOSMakeValid_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern char* (*GEOSGeomType_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeomTypeId_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGetSRID_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern void (*GEOSSetSRID_r)(GEOSContextHandle_t, GEOSGeometry*, int);
extern void* (*GEOSGeom_getUserData_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern void (*GEOSGeom_setUserData_r)(GEOSContextHandle_t, GEOSGeometry*, void*);
extern int (*GEOSGetNumGeometries_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern const GEOSGeometry* (*GEOSGetGeometryN_r)( GEOSContextHandle_t, const GEOSGeometry*, int);
extern int (*GEOSNormalize_r)(GEOSContextHandle_t, GEOSGeometry*);
extern GEOSGeometry* (*GEOSGeom_setPrecision_r)( GEOSContextHandle_t, const GEOSGeometry*, double, int);
extern double (*GEOSGeom_getPrecision_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGetNumInteriorRings_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeomGetNumPoints_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeomGetX_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSGeomGetY_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSGeomGetZ_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern const GEOSGeometry* (*GEOSGetInteriorRingN_r)( GEOSContextHandle_t, const GEOSGeometry*, int);
extern const GEOSGeometry* (*GEOSGetExteriorRing_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGetNumCoordinates_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern const GEOSCoordSequence* (*GEOSGeom_getCoordSeq_r)( GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeom_getDimensions_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeom_getCoordinateDimension_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSGeom_getXMin_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSGeom_getYMin_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSGeom_getXMax_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSGeom_getYMax_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern GEOSGeometry* (*GEOSGeomGetPointN_r)(GEOSContextHandle_t, const GEOSGeometry*, int);
extern GEOSGeometry* (*GEOSGeomGetStartPoint_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern GEOSGeometry* (*GEOSGeomGetEndPoint_r)(GEOSContextHandle_t, const GEOSGeometry*);
extern int (*GEOSArea_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSLength_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern int (*GEOSDistance_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double*);
extern int (*GEOSDistanceIndexed_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double*);
extern int (*GEOSHausdorffDistance_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double*);
extern int (*GEOSHausdorffDistanceDensify_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double, double*);
extern int (*GEOSFrechetDistance_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double*);
extern int (*GEOSFrechetDistanceDensify_r)(GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*, double, double*);
extern int (*GEOSGeomGetLength_r)(GEOSContextHandle_t, const GEOSGeometry*, double*);
extern GEOSCoordSequence* (*GEOSNearestPoints_r)( GEOSContextHandle_t, const GEOSGeometry*, const GEOSGeometry*);
extern int (*GEOSOrientationIndex_r)(GEOSContextHandle_t, double, double, double, double, double, double);
extern GEOSWKTReader* (*GEOSWKTReader_create_r)( GEOSContextHandle_t);
extern void (*GEOSWKTReader_destroy_r)(GEOSContextHandle_t, GEOSWKTReader*);
extern GEOSGeometry* (*GEOSWKTReader_read_r)(GEOSContextHandle_t, GEOSWKTReader*, const char*);
extern GEOSWKTWriter* (*GEOSWKTWriter_create_r)( GEOSContextHandle_t);
extern void (*GEOSWKTWriter_destroy_r)(GEOSContextHandle_t, GEOSWKTWriter*);
extern char* (*GEOSWKTWriter_write_r)(GEOSContextHandle_t, GEOSWKTWriter*, const GEOSGeometry*);
extern void (*GEOSWKTWriter_setTrim_r)(GEOSContextHandle_t, GEOSWKTWriter*, char);
extern void (*GEOSWKTWriter_setRoundingPrecision_r)(GEOSContextHandle_t, GEOSWKTWriter*, int);
extern void (*GEOSWKTWriter_setOutputDimension_r)(GEOSContextHandle_t, GEOSWKTWriter*, int);
extern int (*GEOSWKTWriter_getOutputDimension_r)(GEOSContextHandle_t, GEOSWKTWriter*);
extern void (*GEOSWKTWriter_setOld3D_r)(GEOSContextHandle_t, GEOSWKTWriter*, int);
extern GEOSWKBReader* (*GEOSWKBReader_create_r)( GEOSContextHandle_t);
extern void (*GEOSWKBReader_destroy_r)(GEOSContextHandle_t, GEOSWKBReader*);
extern GEOSGeometry* (*GEOSWKBReader_read_r)(GEOSContextHandle_t, GEOSWKBReader*, const unsigned char*, size_t);
extern GEOSGeometry* (*GEOSWKBReader_readHEX_r)( GEOSContextHandle_t, GEOSWKBReader*, const unsigned char*, size_t);
extern GEOSWKBWriter* (*GEOSWKBWriter_create_r)( GEOSContextHandle_t);
extern void (*GEOSWKBWriter_destroy_r)(GEOSContextHandle_t, GEOSWKBWriter*);
extern unsigned char* (*GEOSWKBWriter_write_r)( GEOSContextHandle_t, GEOSWKBWriter*, const GEOSGeometry*, size_t*);
extern unsigned char* (*GEOSWKBWriter_writeHEX_r)( GEOSContextHandle_t, GEOSWKBWriter*, const GEOSGeometry*, size_t*);
extern int (*GEOSWKBWriter_getOutputDimension_r)( GEOSContextHandle_t, const GEOSWKBWriter*);
extern void (*GEOSWKBWriter_setOutputDimension_r)( GEOSContextHandle_t, GEOSWKBWriter*, int);
extern int (*GEOSWKBWriter_getByteOrder_r)(GEOSContextHandle_t, const GEOSWKBWriter*);
extern void (*GEOSWKBWriter_setByteOrder_r)(GEOSContextHandle_t, GEOSWKBWriter*, int);
extern char (*GEOSWKBWriter_getIncludeSRID_r)(GEOSContextHandle_t, const GEOSWKBWriter*);
extern void (*GEOSWKBWriter_setIncludeSRID_r)(GEOSContextHandle_t, GEOSWKBWriter*, const char);
extern void (*GEOSFree_r)(GEOSContextHandle_t, void*);


// defined in libgeos-version.c, where it is safe to #include geos_c.h
SEXP libgeos_geos_version();

static const R_CallMethodDef CallEntries[] = {
  {"libgeos_geos_version", (DL_FUNC) &libgeos_geos_version, 0},
  {NULL, NULL, 0}
};


void R_init_libgeos(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);

  /* used by external packages linking to libgeos from C */
    R_RegisterCCallable("libgeos", "initGEOS_r", (DL_FUNC) &initGEOS_r);
    R_RegisterCCallable("libgeos", "finishGEOS_r", (DL_FUNC) &finishGEOS_r);
    R_RegisterCCallable("libgeos", "GEOS_init_r", (DL_FUNC) &GEOS_init_r);
    R_RegisterCCallable("libgeos", "GEOS_finish_r", (DL_FUNC) &GEOS_finish_r);
    R_RegisterCCallable("libgeos", "GEOSContext_setNoticeHandler_r", (DL_FUNC) &GEOSContext_setNoticeHandler_r);
    R_RegisterCCallable("libgeos", "GEOSContext_setErrorHandler_r", (DL_FUNC) &GEOSContext_setErrorHandler_r);
    R_RegisterCCallable("libgeos", "GEOSContext_setNoticeMessageHandler_r", (DL_FUNC) &GEOSContext_setNoticeMessageHandler_r);
    R_RegisterCCallable("libgeos", "GEOSContext_setErrorMessageHandler_r", (DL_FUNC) &GEOSContext_setErrorMessageHandler_r);
    R_RegisterCCallable("libgeos", "GEOSversion", (DL_FUNC) &GEOSversion);
    R_RegisterCCallable("libgeos", "GEOSGeomFromWKT_r", (DL_FUNC) &GEOSGeomFromWKT_r);
    R_RegisterCCallable("libgeos", "GEOSGeomToWKT_r", (DL_FUNC) &GEOSGeomToWKT_r);
    R_RegisterCCallable("libgeos", "GEOS_getWKBOutputDims_r", (DL_FUNC) &GEOS_getWKBOutputDims_r);
    R_RegisterCCallable("libgeos", "GEOS_setWKBOutputDims_r", (DL_FUNC) &GEOS_setWKBOutputDims_r);
    R_RegisterCCallable("libgeos", "GEOS_getWKBByteOrder_r", (DL_FUNC) &GEOS_getWKBByteOrder_r);
    R_RegisterCCallable("libgeos", "GEOS_setWKBByteOrder_r", (DL_FUNC) &GEOS_setWKBByteOrder_r);
    R_RegisterCCallable("libgeos", "GEOSGeomFromWKB_buf_r", (DL_FUNC) &GEOSGeomFromWKB_buf_r);
    R_RegisterCCallable("libgeos", "GEOSGeomToWKB_buf_r", (DL_FUNC) &GEOSGeomToWKB_buf_r);
    R_RegisterCCallable("libgeos", "GEOSGeomFromHEX_buf_r", (DL_FUNC) &GEOSGeomFromHEX_buf_r);
    R_RegisterCCallable("libgeos", "GEOSGeomToHEX_buf_r", (DL_FUNC) &GEOSGeomToHEX_buf_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_create_r", (DL_FUNC) &GEOSCoordSeq_create_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_clone_r", (DL_FUNC) &GEOSCoordSeq_clone_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_destroy_r", (DL_FUNC) &GEOSCoordSeq_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setX_r", (DL_FUNC) &GEOSCoordSeq_setX_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setY_r", (DL_FUNC) &GEOSCoordSeq_setY_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setZ_r", (DL_FUNC) &GEOSCoordSeq_setZ_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setXY_r", (DL_FUNC) &GEOSCoordSeq_setXY_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setXYZ_r", (DL_FUNC) &GEOSCoordSeq_setXYZ_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_setOrdinate_r", (DL_FUNC) &GEOSCoordSeq_setOrdinate_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getX_r", (DL_FUNC) &GEOSCoordSeq_getX_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getY_r", (DL_FUNC) &GEOSCoordSeq_getY_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getZ_r", (DL_FUNC) &GEOSCoordSeq_getZ_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getXY_r", (DL_FUNC) &GEOSCoordSeq_getXY_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getXYZ_r", (DL_FUNC) &GEOSCoordSeq_getXYZ_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getOrdinate_r", (DL_FUNC) &GEOSCoordSeq_getOrdinate_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getSize_r", (DL_FUNC) &GEOSCoordSeq_getSize_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_getDimensions_r", (DL_FUNC) &GEOSCoordSeq_getDimensions_r);
    R_RegisterCCallable("libgeos", "GEOSCoordSeq_isCCW_r", (DL_FUNC) &GEOSCoordSeq_isCCW_r);
    R_RegisterCCallable("libgeos", "GEOSProject_r", (DL_FUNC) &GEOSProject_r);
    R_RegisterCCallable("libgeos", "GEOSInterpolate_r", (DL_FUNC) &GEOSInterpolate_r);
    R_RegisterCCallable("libgeos", "GEOSProjectNormalized_r", (DL_FUNC) &GEOSProjectNormalized_r);
    R_RegisterCCallable("libgeos", "GEOSInterpolateNormalized_r", (DL_FUNC) &GEOSInterpolateNormalized_r);
    R_RegisterCCallable("libgeos", "GEOSBuffer_r", (DL_FUNC) &GEOSBuffer_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_create_r", (DL_FUNC) &GEOSBufferParams_create_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_destroy_r", (DL_FUNC) &GEOSBufferParams_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_setEndCapStyle_r", (DL_FUNC) &GEOSBufferParams_setEndCapStyle_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_setJoinStyle_r", (DL_FUNC) &GEOSBufferParams_setJoinStyle_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_setMitreLimit_r", (DL_FUNC) &GEOSBufferParams_setMitreLimit_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_setQuadrantSegments_r", (DL_FUNC) &GEOSBufferParams_setQuadrantSegments_r);
    R_RegisterCCallable("libgeos", "GEOSBufferParams_setSingleSided_r", (DL_FUNC) &GEOSBufferParams_setSingleSided_r);
    R_RegisterCCallable("libgeos", "GEOSBufferWithParams_r", (DL_FUNC) &GEOSBufferWithParams_r);
    R_RegisterCCallable("libgeos", "GEOSBufferWithStyle_r", (DL_FUNC) &GEOSBufferWithStyle_r);
    R_RegisterCCallable("libgeos", "GEOSSingleSidedBuffer_r", (DL_FUNC) &GEOSSingleSidedBuffer_r);
    R_RegisterCCallable("libgeos", "GEOSOffsetCurve_r", (DL_FUNC) &GEOSOffsetCurve_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createPoint_r", (DL_FUNC) &GEOSGeom_createPoint_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createPointFromXY_r", (DL_FUNC) &GEOSGeom_createPointFromXY_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createEmptyPoint_r", (DL_FUNC) &GEOSGeom_createEmptyPoint_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createLinearRing_r", (DL_FUNC) &GEOSGeom_createLinearRing_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createLineString_r", (DL_FUNC) &GEOSGeom_createLineString_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createEmptyLineString_r", (DL_FUNC) &GEOSGeom_createEmptyLineString_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createEmptyPolygon_r", (DL_FUNC) &GEOSGeom_createEmptyPolygon_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createPolygon_r", (DL_FUNC) &GEOSGeom_createPolygon_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createCollection_r", (DL_FUNC) &GEOSGeom_createCollection_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_createEmptyCollection_r", (DL_FUNC) &GEOSGeom_createEmptyCollection_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_clone_r", (DL_FUNC) &GEOSGeom_clone_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_destroy_r", (DL_FUNC) &GEOSGeom_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSEnvelope_r", (DL_FUNC) &GEOSEnvelope_r);
    R_RegisterCCallable("libgeos", "GEOSIntersection_r", (DL_FUNC) &GEOSIntersection_r);
    R_RegisterCCallable("libgeos", "GEOSConvexHull_r", (DL_FUNC) &GEOSConvexHull_r);
    R_RegisterCCallable("libgeos", "GEOSMinimumRotatedRectangle_r", (DL_FUNC) &GEOSMinimumRotatedRectangle_r);
    R_RegisterCCallable("libgeos", "GEOSMinimumWidth_r", (DL_FUNC) &GEOSMinimumWidth_r);
    R_RegisterCCallable("libgeos", "GEOSMinimumClearanceLine_r", (DL_FUNC) &GEOSMinimumClearanceLine_r);
    R_RegisterCCallable("libgeos", "GEOSMinimumClearance_r", (DL_FUNC) &GEOSMinimumClearance_r);
    R_RegisterCCallable("libgeos", "GEOSDifference_r", (DL_FUNC) &GEOSDifference_r);
    R_RegisterCCallable("libgeos", "GEOSSymDifference_r", (DL_FUNC) &GEOSSymDifference_r);
    R_RegisterCCallable("libgeos", "GEOSBoundary_r", (DL_FUNC) &GEOSBoundary_r);
    R_RegisterCCallable("libgeos", "GEOSUnion_r", (DL_FUNC) &GEOSUnion_r);
    R_RegisterCCallable("libgeos", "GEOSUnaryUnion_r", (DL_FUNC) &GEOSUnaryUnion_r);
    R_RegisterCCallable("libgeos", "GEOSCoverageUnion_r", (DL_FUNC) &GEOSCoverageUnion_r);
    R_RegisterCCallable("libgeos", "GEOSUnionCascaded_r", (DL_FUNC) &GEOSUnionCascaded_r);
    R_RegisterCCallable("libgeos", "GEOSPointOnSurface_r", (DL_FUNC) &GEOSPointOnSurface_r);
    R_RegisterCCallable("libgeos", "GEOSGetCentroid_r", (DL_FUNC) &GEOSGetCentroid_r);
    R_RegisterCCallable("libgeos", "GEOSMinimumBoundingCircle_r", (DL_FUNC) &GEOSMinimumBoundingCircle_r);
    R_RegisterCCallable("libgeos", "GEOSNode_r", (DL_FUNC) &GEOSNode_r);
    R_RegisterCCallable("libgeos", "GEOSClipByRect_r", (DL_FUNC) &GEOSClipByRect_r);
    R_RegisterCCallable("libgeos", "GEOSPolygonize_r", (DL_FUNC) &GEOSPolygonize_r);
    R_RegisterCCallable("libgeos", "GEOSPolygonize_valid_r", (DL_FUNC) &GEOSPolygonize_valid_r);
    R_RegisterCCallable("libgeos", "GEOSPolygonizer_getCutEdges_r", (DL_FUNC) &GEOSPolygonizer_getCutEdges_r);
    R_RegisterCCallable("libgeos", "GEOSPolygonize_full_r", (DL_FUNC) &GEOSPolygonize_full_r);
    R_RegisterCCallable("libgeos", "GEOSBuildArea_r", (DL_FUNC) &GEOSBuildArea_r);
    R_RegisterCCallable("libgeos", "GEOSLineMerge_r", (DL_FUNC) &GEOSLineMerge_r);
    R_RegisterCCallable("libgeos", "GEOSReverse_r", (DL_FUNC) &GEOSReverse_r);
    R_RegisterCCallable("libgeos", "GEOSSimplify_r", (DL_FUNC) &GEOSSimplify_r);
    R_RegisterCCallable("libgeos", "GEOSTopologyPreserveSimplify_r", (DL_FUNC) &GEOSTopologyPreserveSimplify_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_extractUniquePoints_r", (DL_FUNC) &GEOSGeom_extractUniquePoints_r);
    R_RegisterCCallable("libgeos", "GEOSSharedPaths_r", (DL_FUNC) &GEOSSharedPaths_r);
    R_RegisterCCallable("libgeos", "GEOSSnap_r", (DL_FUNC) &GEOSSnap_r);
    R_RegisterCCallable("libgeos", "GEOSDelaunayTriangulation_r", (DL_FUNC) &GEOSDelaunayTriangulation_r);
    R_RegisterCCallable("libgeos", "GEOSVoronoiDiagram_r", (DL_FUNC) &GEOSVoronoiDiagram_r);
    R_RegisterCCallable("libgeos", "GEOSSegmentIntersection_r", (DL_FUNC) &GEOSSegmentIntersection_r);
    R_RegisterCCallable("libgeos", "GEOSDisjoint_r", (DL_FUNC) &GEOSDisjoint_r);
    R_RegisterCCallable("libgeos", "GEOSTouches_r", (DL_FUNC) &GEOSTouches_r);
    R_RegisterCCallable("libgeos", "GEOSIntersects_r", (DL_FUNC) &GEOSIntersects_r);
    R_RegisterCCallable("libgeos", "GEOSCrosses_r", (DL_FUNC) &GEOSCrosses_r);
    R_RegisterCCallable("libgeos", "GEOSWithin_r", (DL_FUNC) &GEOSWithin_r);
    R_RegisterCCallable("libgeos", "GEOSContains_r", (DL_FUNC) &GEOSContains_r);
    R_RegisterCCallable("libgeos", "GEOSOverlaps_r", (DL_FUNC) &GEOSOverlaps_r);
    R_RegisterCCallable("libgeos", "GEOSEquals_r", (DL_FUNC) &GEOSEquals_r);
    R_RegisterCCallable("libgeos", "GEOSEqualsExact_r", (DL_FUNC) &GEOSEqualsExact_r);
    R_RegisterCCallable("libgeos", "GEOSCovers_r", (DL_FUNC) &GEOSCovers_r);
    R_RegisterCCallable("libgeos", "GEOSCoveredBy_r", (DL_FUNC) &GEOSCoveredBy_r);
    R_RegisterCCallable("libgeos", "GEOSPrepare_r", (DL_FUNC) &GEOSPrepare_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedGeom_destroy_r", (DL_FUNC) &GEOSPreparedGeom_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedContains_r", (DL_FUNC) &GEOSPreparedContains_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedContainsProperly_r", (DL_FUNC) &GEOSPreparedContainsProperly_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedCoveredBy_r", (DL_FUNC) &GEOSPreparedCoveredBy_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedCovers_r", (DL_FUNC) &GEOSPreparedCovers_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedCrosses_r", (DL_FUNC) &GEOSPreparedCrosses_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedDisjoint_r", (DL_FUNC) &GEOSPreparedDisjoint_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedIntersects_r", (DL_FUNC) &GEOSPreparedIntersects_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedOverlaps_r", (DL_FUNC) &GEOSPreparedOverlaps_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedTouches_r", (DL_FUNC) &GEOSPreparedTouches_r);
    R_RegisterCCallable("libgeos", "GEOSPreparedWithin_r", (DL_FUNC) &GEOSPreparedWithin_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_create_r", (DL_FUNC) &GEOSSTRtree_create_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_insert_r", (DL_FUNC) &GEOSSTRtree_insert_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_query_r", (DL_FUNC) &GEOSSTRtree_query_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_nearest_r", (DL_FUNC) &GEOSSTRtree_nearest_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_nearest_generic_r", (DL_FUNC) &GEOSSTRtree_nearest_generic_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_iterate_r", (DL_FUNC) &GEOSSTRtree_iterate_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_remove_r", (DL_FUNC) &GEOSSTRtree_remove_r);
    R_RegisterCCallable("libgeos", "GEOSSTRtree_destroy_r", (DL_FUNC) &GEOSSTRtree_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSisEmpty_r", (DL_FUNC) &GEOSisEmpty_r);
    R_RegisterCCallable("libgeos", "GEOSisSimple_r", (DL_FUNC) &GEOSisSimple_r);
    R_RegisterCCallable("libgeos", "GEOSisRing_r", (DL_FUNC) &GEOSisRing_r);
    R_RegisterCCallable("libgeos", "GEOSHasZ_r", (DL_FUNC) &GEOSHasZ_r);
    R_RegisterCCallable("libgeos", "GEOSisClosed_r", (DL_FUNC) &GEOSisClosed_r);
    R_RegisterCCallable("libgeos", "GEOSRelatePattern_r", (DL_FUNC) &GEOSRelatePattern_r);
    R_RegisterCCallable("libgeos", "GEOSRelate_r", (DL_FUNC) &GEOSRelate_r);
    R_RegisterCCallable("libgeos", "GEOSRelatePatternMatch_r", (DL_FUNC) &GEOSRelatePatternMatch_r);
    R_RegisterCCallable("libgeos", "GEOSRelateBoundaryNodeRule_r", (DL_FUNC) &GEOSRelateBoundaryNodeRule_r);
    R_RegisterCCallable("libgeos", "GEOSisValid_r", (DL_FUNC) &GEOSisValid_r);
    R_RegisterCCallable("libgeos", "GEOSisValidReason_r", (DL_FUNC) &GEOSisValidReason_r);
    R_RegisterCCallable("libgeos", "GEOSisValidDetail_r", (DL_FUNC) &GEOSisValidDetail_r);
    R_RegisterCCallable("libgeos", "GEOSMakeValid_r", (DL_FUNC) &GEOSMakeValid_r);
    R_RegisterCCallable("libgeos", "GEOSGeomType_r", (DL_FUNC) &GEOSGeomType_r);
    R_RegisterCCallable("libgeos", "GEOSGeomTypeId_r", (DL_FUNC) &GEOSGeomTypeId_r);
    R_RegisterCCallable("libgeos", "GEOSGetSRID_r", (DL_FUNC) &GEOSGetSRID_r);
    R_RegisterCCallable("libgeos", "GEOSSetSRID_r", (DL_FUNC) &GEOSSetSRID_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getUserData_r", (DL_FUNC) &GEOSGeom_getUserData_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_setUserData_r", (DL_FUNC) &GEOSGeom_setUserData_r);
    R_RegisterCCallable("libgeos", "GEOSGetNumGeometries_r", (DL_FUNC) &GEOSGetNumGeometries_r);
    R_RegisterCCallable("libgeos", "GEOSGetGeometryN_r", (DL_FUNC) &GEOSGetGeometryN_r);
    R_RegisterCCallable("libgeos", "GEOSNormalize_r", (DL_FUNC) &GEOSNormalize_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_setPrecision_r", (DL_FUNC) &GEOSGeom_setPrecision_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getPrecision_r", (DL_FUNC) &GEOSGeom_getPrecision_r);
    R_RegisterCCallable("libgeos", "GEOSGetNumInteriorRings_r", (DL_FUNC) &GEOSGetNumInteriorRings_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetNumPoints_r", (DL_FUNC) &GEOSGeomGetNumPoints_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetX_r", (DL_FUNC) &GEOSGeomGetX_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetY_r", (DL_FUNC) &GEOSGeomGetY_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetZ_r", (DL_FUNC) &GEOSGeomGetZ_r);
    R_RegisterCCallable("libgeos", "GEOSGetInteriorRingN_r", (DL_FUNC) &GEOSGetInteriorRingN_r);
    R_RegisterCCallable("libgeos", "GEOSGetExteriorRing_r", (DL_FUNC) &GEOSGetExteriorRing_r);
    R_RegisterCCallable("libgeos", "GEOSGetNumCoordinates_r", (DL_FUNC) &GEOSGetNumCoordinates_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getCoordSeq_r", (DL_FUNC) &GEOSGeom_getCoordSeq_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getDimensions_r", (DL_FUNC) &GEOSGeom_getDimensions_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getCoordinateDimension_r", (DL_FUNC) &GEOSGeom_getCoordinateDimension_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getXMin_r", (DL_FUNC) &GEOSGeom_getXMin_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getYMin_r", (DL_FUNC) &GEOSGeom_getYMin_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getXMax_r", (DL_FUNC) &GEOSGeom_getXMax_r);
    R_RegisterCCallable("libgeos", "GEOSGeom_getYMax_r", (DL_FUNC) &GEOSGeom_getYMax_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetPointN_r", (DL_FUNC) &GEOSGeomGetPointN_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetStartPoint_r", (DL_FUNC) &GEOSGeomGetStartPoint_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetEndPoint_r", (DL_FUNC) &GEOSGeomGetEndPoint_r);
    R_RegisterCCallable("libgeos", "GEOSArea_r", (DL_FUNC) &GEOSArea_r);
    R_RegisterCCallable("libgeos", "GEOSLength_r", (DL_FUNC) &GEOSLength_r);
    R_RegisterCCallable("libgeos", "GEOSDistance_r", (DL_FUNC) &GEOSDistance_r);
    R_RegisterCCallable("libgeos", "GEOSDistanceIndexed_r", (DL_FUNC) &GEOSDistanceIndexed_r);
    R_RegisterCCallable("libgeos", "GEOSHausdorffDistance_r", (DL_FUNC) &GEOSHausdorffDistance_r);
    R_RegisterCCallable("libgeos", "GEOSHausdorffDistanceDensify_r", (DL_FUNC) &GEOSHausdorffDistanceDensify_r);
    R_RegisterCCallable("libgeos", "GEOSFrechetDistance_r", (DL_FUNC) &GEOSFrechetDistance_r);
    R_RegisterCCallable("libgeos", "GEOSFrechetDistanceDensify_r", (DL_FUNC) &GEOSFrechetDistanceDensify_r);
    R_RegisterCCallable("libgeos", "GEOSGeomGetLength_r", (DL_FUNC) &GEOSGeomGetLength_r);
    R_RegisterCCallable("libgeos", "GEOSNearestPoints_r", (DL_FUNC) &GEOSNearestPoints_r);
    R_RegisterCCallable("libgeos", "GEOSOrientationIndex_r", (DL_FUNC) &GEOSOrientationIndex_r);
    R_RegisterCCallable("libgeos", "GEOSWKTReader_create_r", (DL_FUNC) &GEOSWKTReader_create_r);
    R_RegisterCCallable("libgeos", "GEOSWKTReader_destroy_r", (DL_FUNC) &GEOSWKTReader_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSWKTReader_read_r", (DL_FUNC) &GEOSWKTReader_read_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_create_r", (DL_FUNC) &GEOSWKTWriter_create_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_destroy_r", (DL_FUNC) &GEOSWKTWriter_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_write_r", (DL_FUNC) &GEOSWKTWriter_write_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_setTrim_r", (DL_FUNC) &GEOSWKTWriter_setTrim_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_setRoundingPrecision_r", (DL_FUNC) &GEOSWKTWriter_setRoundingPrecision_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_setOutputDimension_r", (DL_FUNC) &GEOSWKTWriter_setOutputDimension_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_getOutputDimension_r", (DL_FUNC) &GEOSWKTWriter_getOutputDimension_r);
    R_RegisterCCallable("libgeos", "GEOSWKTWriter_setOld3D_r", (DL_FUNC) &GEOSWKTWriter_setOld3D_r);
    R_RegisterCCallable("libgeos", "GEOSWKBReader_create_r", (DL_FUNC) &GEOSWKBReader_create_r);
    R_RegisterCCallable("libgeos", "GEOSWKBReader_destroy_r", (DL_FUNC) &GEOSWKBReader_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSWKBReader_read_r", (DL_FUNC) &GEOSWKBReader_read_r);
    R_RegisterCCallable("libgeos", "GEOSWKBReader_readHEX_r", (DL_FUNC) &GEOSWKBReader_readHEX_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_create_r", (DL_FUNC) &GEOSWKBWriter_create_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_destroy_r", (DL_FUNC) &GEOSWKBWriter_destroy_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_write_r", (DL_FUNC) &GEOSWKBWriter_write_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_writeHEX_r", (DL_FUNC) &GEOSWKBWriter_writeHEX_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_getOutputDimension_r", (DL_FUNC) &GEOSWKBWriter_getOutputDimension_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_setOutputDimension_r", (DL_FUNC) &GEOSWKBWriter_setOutputDimension_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_getByteOrder_r", (DL_FUNC) &GEOSWKBWriter_getByteOrder_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_setByteOrder_r", (DL_FUNC) &GEOSWKBWriter_setByteOrder_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_getIncludeSRID_r", (DL_FUNC) &GEOSWKBWriter_getIncludeSRID_r);
    R_RegisterCCallable("libgeos", "GEOSWKBWriter_setIncludeSRID_r", (DL_FUNC) &GEOSWKBWriter_setIncludeSRID_r);
    R_RegisterCCallable("libgeos", "GEOSFree_r", (DL_FUNC) &GEOSFree_r);
}
